modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ArisuwuMei/ChickensGiveFeathers/issues"
license = "$license"

[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
authors = "$authors"
description = "$description"
logoFile = "$icon"

[[dependencies.$id]]
modId = "neoforge"
type = "required"
versionRange = "[0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.$id]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"