modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ArisuwuMei/ChickensGiveFeathers/issues"
license = "$license"

[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
authors = "$authors"
description = "$description"
logoFile = "$icon"

[[dependencies.$id]]
modId = "neoforge"
type = "required"
versionRange = "[$neoforge_version_range,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.$id]]
modId = "minecraft"
type = "required"
versionRange = "[$minecraft_version,)"
ordering = "NONE"
side = "BOTH"